version: "3.8"

services:
  oracle-db:
    build:
      context: ./oracledb-21.3.0
      dockerfile: Dockerfile
      args:
        - DB_EDITION=se2
        - BASE_IMAGE=oraclelinux:8
        - SLIMMING=false
    environment:
      - ORACLE_SID=ORACLEDB
      - ORACLE_PDB=ORACLEPDB1
      - ORACLE_PWD=123456789a
      - ORACLE_EDITION=standard
    ports:
      - 1521:1521
      - 5500:5500
      - 2484:2484
    volumes:
      - oradata:/opt/oracle/oradata
    ulimits:
      nofile:
        soft: 65536
        hard: 65536
volumes:
  oradata:
